/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class edu_sfsu_cs_orange_ocr_OpencvNativeClass */
#include<stdio.h>
#include <string>
#include <assert.h>
using namespace std;


#include <opencv2/opencv.hpp>
#include "opencv2/highgui/highgui.hpp"
#include "opencv2/imgproc/imgproc.hpp"
#include "opencv2/core/core.hpp"
using namespace cv;
#ifndef _Included_edu_sfsu_cs_orange_ocr_OpencvNativeClass
#define _Included_edu_sfsu_cs_orange_ocr_OpencvNativeClass
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     edu_sfsu_cs_orange_ocr_OpencvNativeClass
 * Method:    BinarizeShafait
 * Signature: (Ljava/lang/String;J)V
 */
JNIEXPORT void JNICALL Java_edu_sfsu_cs_orange_ocr_OpencvNativeClass_BinarizeShafait
  (JNIEnv *, jclass, jlong input, jlong output);

JNIEXPORT void JNICALL Java_edu_sfsu_cs_orange_ocr_OpencvNativeClass_BinarizeBG
        (JNIEnv *, jclass, jlong BG, jlong input, jlong output);

#ifdef __cplusplus
}
#endif
#endif
