/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class edu_sfsu_cs_orange_ocr_ParsingNativeClass */
#include <stdio.h>
#include <regex>
 #include <string>
#include <fstream>
#include <iostream>
#include <stdexcept>
#include <sstream>
#include <algorithm>

using namespace std;
#ifndef _Included_edu_sfsu_cs_orange_ocr_ParsingNativeClass
#define _Included_edu_sfsu_cs_orange_ocr_ParsingNativeClass
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     edu_sfsu_cs_orange_ocr_ParsingNativeClass
 * Method:    ParseAddress
 * Signature: (Ljava/lang/String;Ljava/lang/String;)I
 */
JNIEXPORT jstring JNICALL Java_edu_sfsu_cs_orange_ocr_ParsingNativeClass_ParseAddress
  (JNIEnv *, jclass, jstring input);

#ifdef __cplusplus
}
#endif
#endif
